Blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.about),
    path('posts/',include('posts.urls')),
    path('users/',include('users.urls')),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),

]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.posts_list,name="list"),
    path('new-post/',views.post_new,name="new-post"),
    path('<slug:slug>',views.post_page,name="page"),
    path('update/<slug:slug>', views.update_post, name='update'),
    path('delete/<slug:slug>', views.delete_post, name='delete'),
    path('comment/<slug:slug>', views.create_comment, name="comment"),
    path('categories/', views.categories_list, name="categories"),
    path('category/<int:cat_id>', views.category, name="category"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register_view,name="register"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.

class Category(models.Model):
    name = models.TextField()
    description = models.TextField()

    def __str__(self):
        return f'{self.name}'
    
class Post(models.Model):
    title = models.CharField(max_length=75)
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    slug = models.SlugField()
    banner = models.ImageField(default='logo-poli.png', blank = True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    categories = models.ManyToManyField(Category, related_name='posts')
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.body}" - {self.author.username}'
    

users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=16)
    email = models.CharField(max_length=75)
    password = models.CharField(max_length=75)
    
    def __str__(self):
        return self.name

posts/forms.py
from django import forms
from .  import models

class CreatePost(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple, queryset=models.Category.objects.all())
    class Meta:
        model = models.Post
        fields = ['title','body','banner','slug','categories']

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = [
            'body',
        ]
        labels = {
            'body': 'Comment',
        }

Blog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render,redirect, get_object_or_404, get_list_or_404
from .models import Post, Comment, Category
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from . import forms
from .forms import CreatePost
# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request,'posts/posts_list.html',{ 'posts': posts })

def post_page(request,slug):
    post = Post.objects.get(slug=slug)
    post_id = post.id
    comments = Comment.objects.filter(post=post_id).order_by('-date')
    cats = post.categories.all()
    return render(request,'posts/post_page.html',{ 'post': post, 'cats' : cats, 'comments': comments })

def update_post(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.method == "POST":
        form = CreatePost(request.POST)
        if form.is_valid():
            post.title = request.POST['title']
            post.date = post.date
            post.banner = request.POST['banner']
            post.body = request.POST['body']
            post.categories.set(form.cleaned_data.get("categories"))
            post.save()
            return redirect("posts:page", slug = slug)

    else:
        form = CreatePost(
            initial={
                "title": post.title,
                "date": post.date,
                "body": post.body,
                "slug": post.slug,
                "banner": post.banner,
            }
        )

    context = {"post": post, "form": form}
    return render(request, "posts/update.html", context)

def delete_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse("posts:list"))

    context = {"post": post}
    return render(request, "posts/delete.html", context)



@login_required(login_url = "/users/login/")
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            newpost.categories.set(form.cleaned_data.get("categories"))
            newpost.save()
            return redirect('posts:list')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

@login_required(login_url="/users/login")
def create_comment(request, slug):
    post = get_object_or_404(Post, slug=slug)
    post_id = post_id = post.id
    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment_author = request.user
            comment_text = form.cleaned_data['body']
            comment = Comment(author=comment_author,
                            body=comment_text,
                            post=post)
            comment.save()
            return redirect("posts:page", slug=slug)
    else:
        form = forms.CommentForm()
    comments = Comment.objects.filter(post=post_id).order_by('-date')
    return render(request, 'posts/comment.html', {'form': form, 'post': post, 'comments': comments})

def category(request, cat_id):
    posts = get_list_or_404(Post,categories=cat_id)
    cat = Category.objects.get(pk=cat_id)
    return render(request, 'posts/category.html', {'posts': posts, 'cat': cat})

def categories_list(request):
    cats = Category.objects.all()
    return render(request, 'posts/categories_list.html', {'cats': cats})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
        else:
            form = UserCreationForm()
    form = UserCreationForm()
    return render(request,"users/register.html",{"form": form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm()

    return render(request,"users/login.html",{"form": form})

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:list")

posts/templates/posts/categories_list.html
{% extends 'layout.html' %}

{% block content %}
        <section class = "category-list">
        <h1 class = "titulo-página">Lista de Categorias</h1>
        {% for cat in cats %}
            <a class = "categoria" href="{% url 'posts:category' cat.id %}">
                <article class="post">
                    <h2>{{ cat.name }}</h2>
                </article>
            </a>
        {% endfor %}
        </section>
{% endblock content %}

posts/templates/posts/category.html
{% extends "layout.html" %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <section class = "category-list">
        <h1 class = "titulo-página">Posts sobre {{ cat }}</h1>
        <p class = "description">{{ cat.description }}</p>
        {% for post in posts %}
            {% if user.is_authenticated%}
            <article class="Postagem">
                <a class = "titulo-post" href="{% url 'posts:page' slug=post.slug %}">
                    <h2 >{{ post.title }}</h2>
                </a>
                <p class = "data"><i>{{ post.date }}</i> by {{ post.author }}</p>
            </article>
            {% endif %}
        {% endfor %}
    </section>
        {% if not user.is_authenticated%}
        <div style="text-align: center;">
            <p style="margin-top: 50px; margin-right: 10px; display: inline-block;"><b>Login</b> to view more posts</p>
            <a href="{% url 'users:login' %}"><button class="edit-button">Login</button></a>
        </div>
        {% endif %}
{% endblock content %}

posts/templates/posts/comment.html
{% extends 'layout.html' %}

{% block content %}
<h1 class = "titulo-página">Comentar Post: "{{ post.title }}"</h1>

<form class = "form-with-validation" action="{% url 'posts:comment' slug=post.slug %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Comentar</button>
</form>

<p><a href="{% url 'posts:page' slug=post.slug %}">Voltar para o Post.</a></p>
{% endblock content %}

posts/templates/posts/delete.html
{% extends 'layout.html' %}
{% block content %}
    <form action="{% url 'posts:delete' slug=post.slug %}" method="post">
        {% csrf_token %}
        <p class = "delete-text">Você tem certeza que deseja apagar o post "{{ post.title }} ({{ post.date }})"?</p>
        <div class = "button">
            <button class = "comment-button" type="submit">Apagar</button>
        <div>
    </form>
{% endblock content %}

posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{% block title %}
    New Post
{% endblock %}

{% block manchete %}
<h1 class = "manchete">Recanto da Postagem</h1>
{% endblock %}

{% block content %}
    <section>
        <h1 class = "titulo-página">Novo Post</h1>
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <button class = "form-submit">Criar Post</button>
        </form>
    </section>
{% endblock %}

posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block manchete %}
<h1 class = "manchete">Recanto da Postagem</h1>
{% endblock %}

{% block content %}
    <section class = "page_content">
        <h1 class = "titulo-página"> {{ post.title }} </h1>
        <section class = "l_cats">
            {% for cat in cats %}<a class = "cats" href="{% url 'posts:category' cat.id %}">{{cat.name}}</a> {% endfor %}
        </section>
        <p class = "data">{{ post.date }}</p>
        <img class="banner" src="{{post.banner.url}}"
             alt = "{{post.title}}"/>
        <p class = "post-text">{{ post.body }}</p>
    </section>
    <section class = "edit">
    {% if  user == post.author or user.is_superuser %}
    <ul class = "alterar">
        <li><a class = "edição" href="{% url 'posts:update' slug=post.slug %}">Editar</a></li>
        <li><a class = "edição" href="{% url 'posts:delete' slug=post.slug %}">Apagar</a></li>
    </ul>
    {% endif %}
    </section>
    <hr>
    <section class = "comments">
        <h1 class = "titulo-página">Comentários</h1>
        <a href="{% url 'posts:comment' post.slug %}"><button class="comment-button">Criar Comentário</button></a>
        {% if post.comment_set.all %}
        <hr style="border: 0.5px solid #c7c7c7; width: 100%; margin: 15px 0px 10px 0px;width: 25%;">
        <section>
    
            
            {% for comment in comments %}
                <div class = "pos-comment">
                    <div class="post-header">
                        <p style="margin:5px 0px 12px 0px;" class="comment-body"><b>{{ comment.author }}</b> - <i>{{ comment.date }}</i></p>
                    </div>
                    <p class = "post-body" style = "text-align:center;">{{ comment.body }}</p>
                    <hr style="border: 0.5px solid #c7c7c7; width: 55%; margin: 15px 0px 10px 0px;">
                </div>
            {% endfor %}
        </section>
        {% endif %}
    </section>

{% endblock %}

posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Lista de Posts
{% endblock %}

{% block manchete %}
<h1 class = "manchete">Recanto da Postagem</h1>
{% endblock %}

{% block content %}
    <section class = "post-list">
    <h1 class = "titulo-página"> Lista de Posts </h1>

    {% for post in posts %}
        <article class  = "Postagem">
            <h2 >
                <a class = "titulo-post" href="{% url 'posts:page' slug=post.slug %}">{{ post.title }}</a>
            </h2>
            <p>{{ post.date }} by {{post.author}}</p>

        </article>
    {% endfor %}
    </section>
{% endblock %}

posts/templates/posts/update.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class = "titulo-página">Atualizar Post: "{{ post.title }}" ({{ post.date }})</h1>
    <form class="form-with-validation" method="POST" action="{% url 'posts:update' post.slug %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Atualizar</button>
    </form>
{% endblock content %}

templates/about.html
{% extends 'layout.html' %}

{% block title %}
    Recanto da Postagem
{% endblock %}

{% block content %}
    <section class = "about-text">
    <p>Navegando entre as abas deste site você será capaz de:</p>
    <ul class = "lista-about">
        <li> Criar Postagens sobre experiências que deseja compartilhar, bem como visualizar postagem de outras pessoas.</li>
        <li> Navegar através das categorias para encontrar os posts que mais te interessam, como esportivos ou culinários.</li> 
        <li>Comentar nos posts de outros usuários para que tenham uma discussão engajante.</li>
    </ul>
    <p>Lembre-se apenas de registrar-se antes de começar a aproveitar os recursos disponíveis!</p>
    
    </section>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Recanto da Postagem
{% endblock %}

{% block manchete %}
<h1 class = "manchete">Recanto da Postagem</h1>
{% endblock %}

{% block content %}
    <p style = "padding-top:20px;"> Neste site você encontrará um lugar confortável e descontraído para compartilhar experiências
        vivenciadas por você, bem como encontrar relatos de outras pessoas. Espera-se que o ambiente
        te ajude a encontrar informações que precise, bem como novos amigos com quem possa compartilhar
        coisas interessantes.
    </p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <title>
        {% block title %}
            Meu Blog
        {% endblock %}
    </title>
</head>

<body>
    <header>
        <div>
            {% block manchete %}
            <h1 class = "manchete">Recanto da Postagem</h1>
            {% endblock %}
            <nav>
                <ul id = "navegação">
                    <li><a class = "cabeçalho" href="/">Home</a></li>
                    <li><a class = "cabeçalho" href="/about"> Sobre</a></li>
                    <li><a class = "cabeçalho" href="{% url 'posts:list' %}"> Lista de Posts</a></li>
                    <li><a class = "cabeçalho" href="{% url 'posts:categories' %}"> Lista de Categorias</a></li>
                    {% if user.is_authenticated %}
                        <li><a class = "cabeçalho" href="{% url 'posts:new-post' %}"> Novo Post </a></li>
                        <li><form class ="logout" action= "{% url 'users:logout'%}" method="post">
                            {% csrf_token %}
                            <button class="logout-button" aria-label="User Logout">Logout</button>
                        </form>
                        </li>
                    {% else %}
                        <li><a class = "cabeçalho" href="{% url 'users:register' %}"> Registre-se </a></li>
                        <li><a class = "cabeçalho" href="{% url 'users:login' %}"> Login </a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>Copyright &#169 2024 Pedro Durante Terciotti.</p>
    </footer>
    
</body>
</html>

users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <h1 class="titulo-página">
        Login
    </h1>
    <form class="form-with-validation" action="/users/login/" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type="hidden" name="next" value= "{{request.GET.next}}"/>
        {% endif %}
        <button class = "form-submit">Submit</button>
    </form>
{% endblock %}

users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
    <h1 class = "titulo-página">Registre-se</h1>
    <form class="form-with-validation" action="/users/register/" method="post">
        {% csrf_token %}
        {{form}}
        <button class = "form-submit">Registrar</button>
    </form>
{% endblock %}